# 各プロジェクト用のトリガー作成後に「代入変数」で以下を設定
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: 
    - -c
    - |
      gcloud compute instances list
      gcloud compute networks list
