steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: bash
      args:
      - -c
      - |
        gcloud beta container clusters get-credentials your-first-cluster-1 --region asia-northeast1 --project yoshimura-test
    - name: 'gcr.io/cloud-builders/kubectl'
      entrypoint: bash
      args:
      - -c
      - |
        kubectl create secret generic cloudsql-instance-credentials --from-file=credentials.json=key.json
        kubectl get secret
        kubectl apply -f k8s.yaml

