apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsql-proxy-service
  name: cloudsql-proxy-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: cloudsql-proxy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloudsql-proxy
  name: cloudsql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command: ["/cloud_sql_proxy",
        "-instances=yoshimura-test:asia-northeast1:test-sql=tcp:0.0.0.0:3306",
                 "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
        ports:
        - containerPort: 3306
          name: cloudsql-proxy
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
            cpu: 500m
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials


